### PR TITLE
sql: Add support for ON CONFLICT REPLACE

### LINKED ISSUE #23: Select doesn't work on tables with "ON CONFLICT REPLACE"
Using Select() on a sqlite3 database table with a "ON CONFLICT REPLACE" constraint results in the following error:

`syntax error: unexpected ON, expecting ',' or ')'`

Code to reproduce:

```
        db, err := sqlittle.Open("test_broken.db")
	if err != nil {
		panic(err)
	}
	defer db.Close()

	err = db.Select("table1", func(r sqlittle.Row) {
		var (
			data int
		)
		_ = r.Scan(&data)
		fmt.Printf("%d\n", data)
	}, "data")

	if err != nil {
		panic(err)
	}
```

The schema is as follows:

`
CREATE TABLE table1 ( data INT, (UNIQUE data) ON CONFLICT REPLACE );
`

### PR DESCRIPTION
**Pull request by Foxtrot**
Fixes #23 

This PR adds support for the `ON CONFLICT REPLACE` table constraint.

Schema: `CREATE TABLE table1 (data INT, UNIQUE(data) ON CONFLICT REPLACE );`
Data: `INSERT INTO table1 (data) VALUES (1);`
Test:
```
{
	db, err := sqlittle.Open("test_broken.db")
	if err != nil {
		panic(err)
	}
	defer db.Close()

	err = db.Select("table1", func(r sqlittle.Row) {
		var (
			data int
		)
		_ = r.Scan(&data)
		fmt.Printf("Data: %d\n", data)
	}, "data")

	if err != nil {
		panic(err)
	}
}
```
Output:
```
>> ./main 
Data: 1
>>
```

### CODE REVIEW

**Comment by Foxtrot** [comment]
Let me know if there's anything it isn't quite right - I've never used Yacc before :)

**Comment by alicebob** [comment]
Hah, nice :)

Could you add a basic test to sql/sql_test.go? Likely add one to `TestCreateTable()`.

I see CI fails. Maybe you see what's wrong, otherwise I'll have a look later.

**Comment by Foxtrot** [comment]
I've realised why the test fails - When I compile `parser.go.y` into `parser.go` it seems to be missing the code for `yyErrorVerbose`, thus it never prints out a simple "syntax error", making the test fail.

I can of course remedy this and fix the tests by hand editing the resulting `parser.go` file, to add a check for `yyErrorVerbose` and the correct error message.

Any thoughts? Submitting a fix that relies on editing auto-generated files is not good practice.

**Comment by alicebob** [comment]
Hi,

I use the same goyacc, so I can't explain the difference you're getting. I changed the code a bit to basically ignore the "on confict", since we don't really care what it is, as long as the SQL is accepted.

I also added the other "ON CONFLICT" options. It still doesn't support them on column constraints, as specified https://sqlite.org/lang_conflict.html, but that's for another time.

**Comment by alicebob** [comment]
I squashed and pushed the code to master. I hope it fixes your case, if not do let me know. Thanks for the issue and the fix!

**Comment by Foxtrot** [comment]
Awesome, thank you for cleaning up the Yacc - this way makes much more sense :)

**Pull request closed without merging**
